site_name: OAuth2 Proxy Documentation
docs_dir: docs
repo_name: oauth2-proxy/oauth2-proxy
repo_url: https://github.com/oauth2-proxy/oauth2-proxy
site_author: OAuth2 Proxy Authors

copyright: Copyright &copy; 2012 - 2024 OAuth2 Proxy Authors

nav:
  - Welcome: index.md
  - Installation: installation.md
  - Behaviour: behaviour.md
  - Configuration:
    - Overview: configuration/overview.md
    - Alpha Configuration: configuration/alpha_config.md
    - OAuth Provider:
      - ADFS: configuration/providers/adfs.md
      - Azure: configuration/providers/azure.md
      - Azure AD: configuration/providers/azure_ad.md
      - Bitbucket: configuration/providers/bitbucket.md
      - DigitalOcean: configuration/providers/digitalocean.md
      - Facebook: configuration/providers/facebook.md
      - Gitea: configuration/providers/gitea.md
      - GitHub: configuration/providers/github.md
      - GitLab: configuration/providers/gitlab.md
      - Google: configuration/providers/google.md
      - Keycloak: configuration/providers/keycloak.md
      - Keycloak OIDC: configuration/providers/keycloak_oidc.md
      - LinkedIn: configuration/providers/linkedin.md
      - Login.gov: configuration/providers/login_gov.md
      - Nextcloud: configuration/providers/nextcloud.md
      - OpenID Connect: configuration/providers/openid_connect.md
    - Session Storage: configuration/sessions.md
    - TLS Configuration: configuration/tls.md
  - Features:
    - Endpoints: features/endpoints.md
  - Community:
    - Contribution Guide: community/contribution.md
    - Security: community/security.md


theme:
  name: material
  logo: /assets/logos/OAuth2_Proxy_filled_icon.svg
  favicon: /assets/logos/OAuth2_Proxy_icon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - content.code.copy

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - autolinks
  - drawio
  - git-revision-date-localized

markdown_extensions:
  - abbr
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oauth2-proxy
  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
